Hello Microverse Project Pull Request
gilberthappi/Hello_Microverse_Project pull request #1
Opened 2023-06-02 13:07 UTC by gilberthappi

2023-06-02 13:35 UTC, mahbubul14 requested changes
Hi @gilberthappi,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ]  Currently, your `README` file is not updated according to the project. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

- [ ] Pull Request should have a short summary describing introduced changes in more detail.

![pull](https://github.com/gilberthappi/Hello_Microverse_Project/assets/70483835/9a37e4dc-e44e-4b36-98b2-84142659e7d8)


###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-03 03:12 UTC, merged

2023-06-03 03:18 UTC, gilberthappi commented
Updating css file
Updating Readme file

2023-06-07 22:38 UTC, bobb-Rob reviewed
## STATUS: CHANGES REQUIRED ♻️
Hi @gilberthappi, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️

- [ ] Please note that it is not best practice to merge pull request that has not been approved.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 22:38 UTC, bobb-Rob commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
### Great work implementing this project. I know you put in a lot of work to get it through. Kudos 👏 💪

You have not updated your README according to this project, kindly do the following when customizing it to suit this project:

- Remove the Microverse logo. If you have your logo, you can use it but I would advise you to remove it. 🙏
- For the Tech Stack Section, Kindly remove the Server and Database subsections because the technologies listed there are not relevant to this project. For the Client section, kindly include HTML and CSS 👍
- For the Key Features section, kindly highlight what this project is all about. This will make it easy for those who go through this repository to know what was implemented by reading the README.md file. 👍
- For the Prerequisite Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:
    - Installation of Git
    - Installation of NPM
    - A working browser
    - Internet connection
    - A code editor like Visual Studio Code
    - Installation of Live Server plugging in Visual Studio Code
    - Any other tool you can think about
- For the Setup section, kindly add instructions for cloning your repository on a local machine 👍
- For the Install section, kindly add instructions for setting up linters used in this project
- For the Usage section, include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.
- For the MIT section, kindly add a valid LICENSE. You can follow the instructions on the right side of the article attached below to set up a valid LICENSE

https://choosealicense.com/licenses/mit/
Kindly implement all the changes listed above. It will make your README.md file look professional and it will give you an idea of how to set README.md files for most of the projects you will execute as a Microverse student. 👍 💻

2023-06-07 22:38 UTC, bobb-Rob commented on index.html
> +<body>
- [ ] Your pull request description is not professional, kindly update it describing what you implemented in this project. You may use bullet points to highlight them.

2023-06-08 01:22 UTC, Shedrack-Sunday reviewed
Hello @gilberthappi     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- No linter errors ✔️ 
  
# Required Changes  🌵 

- [ ] Firstly. please do not merge a pull request until you get approved. I can see you've exhausted your reviews in the dashboard, but I advise you to open this PR again so you can get approved if you make the changes asked for 👍 

- [ ] As suggested by the previous reviewers, kindly make your PR summary descriptive enough to list changes made in this milestone. A detailed breakdown was provided in this [Link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) provided on the template

- [ ] You have not updated your README according to this project, kindly do the following when customizing it to suit this project:

- Remove the Microverse logo. If you have your logo, you can use it but I would advise you to remove it. 🙏
- For the Tech Stack Section, Kindly remove the Server and Database subsections because the technologies listed there are not relevant to this project. For the Client section, kindly include HTML and CSS 👍
- For the Key Features section, kindly highlight what this project is all about. This will make it easy for those who go through this repository to know what was implemented by reading the README.md file. 👍
- For the Prerequisite Section, kindly add tools that are needed before you can clone this repository on a local machine. Tools like:
* Installation of Git
* Installation of NPM
* A working browser
* Internet connection

- For the Setup section, kindly add instructions for cloning your repository on a local machine 👍
- For the Install section, kindly add instructions for setting up linters used in this project
- For the Usage section, include instructions for opening this project on a browser. For example, opening the project by launching the Live Server plugging in visual studio code or any other means that you know.
- For the MIT section, kindly add a valid LICENSE. You can follow the instructions on the right side of the article attached below to set up a valid LICENSE

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-08 09:00 UTC, joskalenda reviewed
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @gilberthappi , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 23:29 UTC, gilberthappi commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Thanks

2023-06-08 23:30 UTC, gilberthappi commented on index.html
> +</html>
thanks buddy

2023-06-09 07:42 UTC, Efiamotu-1 reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif) 

You have submitted a pull request that has already been merged, please it is a requirement that your pull request remains open so that reviewers can perform their reviews, a merged pull request makes it difficult to require changes for the student.

- [ ] please see this [students readme](https://github.com/Mike111222/Hello-Microverse-Project/blob/main/README.md) as a good example of how your readme should look like before resubmitting

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._